### ISSUE TITLE
compilation of 'llvm-project' still doesn't like `ccache`

### ISSUE THREAD

**Issue by lemzwerg** [freetype/freetype2-testing#118]
Trying to compile the fuzzer using commit 54e76bef6f0d there are still problems in 'llvm-project' with activated `ccache` support. Cmake (version 3.22.1) configuration soon aborts with

```
+ cmake -GNinja ../llvm \
  -DCMAKE_BUILD_TYPE=Release \
  '-DLLVM_ENABLE_PROJECTS=libcxx;libcxxabi' \
  '-DCMAKE_C_COMPILER=ccache clang' \
  '-DCMAKE_CXX_COMPILER=ccache clang++' \
  -DLLVM_USE_SANITIZER=MemoryWithOrigins \
  -DLIBCXX_ENABLE_SHARED=OFF \
  -DLIBCXXABI_ENABLE_SHARED=OFF
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Didn't find assembler
CMake Error at CMakeLists.txt:44 (project):
  The CMAKE_C_COMPILER:                                                                                           

    ccache clang

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:44 (project):
  The CMAKE_CXX_COMPILER:

    ccache clang++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:44 (project):
  No CMAKE_ASM_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```

**Comment by bungeman** [comment]
It looks like when setting `CC="ccache clang"` that CMake parses this into `CMAKE_C_COMPILER=ccache` and `CMAKE_C_COMPILER_ARG1=clang`. This sort-of worked for the fuzzer CMake because it is built without setting `CMAKE_C_COMPILER` and does no tests (like `try_compile`). With the libcxx build `CMAKE_C_COMPILER` is being set directly to the value of `${CC}` which it turns out may not be what is wanted.

It looks like what CMake really wants here is for users to set `CMAKE_C_COMPILER=clang` and `CMAKE_CXX_COMPILER_LAUNCHER=ccache`, which allows it to directly call the compiler directly when it wants to but then use the "launcher" in the actual build. However, it may end up making more sense to just remove the `CMAKE_C_COMPILER` and let `${CC}` just be parsed, which treats `ccache` as the actual compiler (it kind-of is) with `clang` as a mandatory first parameter (which it also kind-of is).
