### ISSUE TITLE
llvm-project: `error: destructor cannot be marked constexpr`

### ISSUE THREAD

**Issue by lemzwerg** [freetype/freetype2-testing#120]
[f30d54be23478ff1963365a64bc8a86a6e32234b]

Using clang version 9.0.1, compilation of llvm-project fails with

```
In file included from
  .../freetype2-testing/external/llvm-project/libcxx/src/optional.cpp:9:
.../freetype2-testing/external/llvm-project/build/include/c++/v1/optional:224:5:
  error: destructor cannot be marked constexpr
    _LIBCPP_CONSTEXPR_AFTER_CXX17 ~__optional_destruct_base()
    ^
.../freetype2-testing/external/llvm-project/build/include/c++/v1/__config:1065:41:
  note: expanded from macro '_LIBCPP_CONSTEXPR_AFTER_CXX17'
#  define _LIBCPP_CONSTEXPR_AFTER_CXX17 constexpr
                                        ^
```

Is it really necessary to install a newer clang version?  In case this is true I suggest that a clang version test is added to `custom-build.sh`.

**Comment by lemzwerg** [comment]
Sigh.  Looking at https://libcxx.llvm.org/#platform-and-compiler-support clang 9 is indeed to old.  This attitude of so many projects to support only the newest and shiniest versions is really, really annoying.

For example, I'm using openSUSE Leap 15.2, which was released in July 2020 – it contains packages for clang7 and clang9 but nothing newer.  I now have to find a proper repository to get clang 12 or 13. Grrrr.

**Comment by bungeman** [comment]
Yeah, the llvm project went to bumping the "major" version each release (see http://blog.llvm.org/2016/12/llvms-new-versioning-scheme.html ). As far as I know clang 9 is more or less clang 3.16 and clang 12 is 3.19 (though I'm sure there probably would have been a jump to 4.0 in there somewhere for any cumulative breaking changes elsewhere in llvm). However, because of the "major" version change distributions shy away from packaging up what are essentially cumulative releases, which is unfortunate.

The libcxx here is currently pinned to the llvm-13 release since I wanted something new enough to be relatively well msan fuzzed already. It might be possible to use an older version of libcxx.

That being said, it appears that openSUSE Leap 15.2 will be end of life in two days, so best to move to 15.3? Though I'm not sure of the default version in 15.3. Not an expert on SUSE, but it looks like in devel:tools:compiler there are clang12 and clang13 packages available for both 15.2 and 15.3.

**Comment by lemzwerg** [comment]
IMHO the thing is that there distributions abound with older clang versions, not only OpenSUSE.  By warning early that you need a recent version the level of frustration can be lowered.  Remember that without 'llvm-project' it was not really important which clang version you have –  now it *must* be one of the two last versions.

Please either add a version test or at least document it in the `README.md` file.

**Comment by bungeman** [comment]
Interestingly, the whole "destructor cannot be marked constexpr" thing is rather awkward. `_LIBCPP_CONSTEXPR_AFTER_CXX17` here is designed to be `constexpr` only after c++17. Most of the build here is actually specifying `-std=c++17`. It appears this is controlled by `_LIBCPP_STD_VER`. Installing `clang-9` locally reproduces and I see that some parts are being built with `-std=c++2a`. Since this is a moving target it isn't surprising that older clang may take issue with it. Note that `clang-10` does work, as does `clang-11`. Note that the `llvm-project` checkout is currently pinned at `llvm-13`, so it isn't necessary to use one of the last two versions of clang.

That being said, one does currently need version 10 or greater. I'll see about testing for that.
